### ISSUE TITLE
Translation hook with bedrock-autoloader

### ISSUE THREAD

**Issue by hyyan** [roots/bedrock#117]
What hook should I use to load translation when I use bedrock-autoloader to load my plugin  ?

**Comment by Foxaii** [comment]
I'm not sure if you ever got this working as you intended, but the way I use translations is by creating an `languages/plugin` folder in `app` that contains `my-plugin-name-en_GB.mo` and `my-plugin-name-en_GB.mo`.

**Comment by M13Kd** [comment]
Kudos en_US.mo should be implemented as well imho.

**Comment by M13Kd** [comment]
Kudos en_US.mo should be implemented as well imho.

**Comment by Foxaii** [comment]
I was just using `en_GB` as an example locale. It will work with others.

**Comment by M13Kd** [comment]
@m13kd m13kd.visvisualstudio.com Xbox Live Developer and Community Amassador for the LIVE team throughout all methods using Windows LIVE Sign In for a dynamic chance to provide the framework and allow me to give a opportunity to myself so as i shared the data legally to help you help me find a way to pay day to day expenses I develop securely in Monroe Georgia due to 10 years homelessness and theft and threats against my live FROM #stopcybertheives. Keep In touch when Its completed thanks. Michael C. Duggan ¤MSFT LIVE Rocks. Mike D PC HELP SERVICE, my donation line PayPal ID- m13kd@aol.com WordPress is cool.


Sent from my MetroPCS 4G Android device

-------- Original message --------
