### ISSUE TITLE
Concerned about future dependency on Ansible

### ISSUE THREAD

**Issue by mattstratton** [roots/bedrock#153]
I'm currently okay with using ansible for configuring the local VM, but I like using the Capistrano based deployment. I actually wouldn't even be against having Ansible be the one that pushes my code, etc.

However, in a closed issue, it was [mentioned](https://github.com/roots/bedrock-ansible/pull/95) that cap support is being retired in favor of using Ansible for all the deployment. I would strongly request that there not be a dependency on having Ansible be hard-coded into the only method used in Bedrock - that is to say, I would prefer to still be able to use the CM of my choice for managing my systems (and I know that Ansible can play nicely with others as long as everyone isn't stepping all over each other). I suppose what I'm requesting is that any system level stuff be something that can be "opt-out" but still maintain the ability to use the excellent deployment framework built here.

**Comment by swalkinshaw** [comment]
I don't think you need to be worried about anything.

[bedrock-ansible](https://github.com/roots/bedrock-ansible) will always be a separate project and there's no way for it to ever really be a "dependency". Even now with Capistrano there's nothing in the actual Bedrock "code" related to Capistrano. It just has its own set of files (`Gemfile`, `Capfile`, configs).

If/when Capistrano is removed, those files will just be moved into its own repo so they won't go away completely. There will just be a section in the `README` about provisioning servers and deploys which will link to it.

The same goes for any other server management software (Chef, Puppet, etc). Since there won't be anything in this repo to do with Ansible (other than the `README`), there really is no dependency anyway.

**Comment by mattstratton** [comment]
Fair enough! The PR referenced was a bit misleading to me. Thanks for
clearing it up.

On Sunday, March 22, 2015, Scott Walkinshaw <notifications@github.com>
wrote:

> I don't think you need to be worried about anything.
>
> bedrock-ansible <https://github.com/roots/bedrock-ansible> will always be
> a separate project and there's no way for it to ever really be a
> "dependency". Even now with Capistrano there's nothing in the actual
> Bedrock "code" related to Capistrano. It just has its own set of files (
> Gemfile, Capfile, configs).
>
> If/when Capistrano is removed, those files will just be moved into its own
> repo so they won't go away completely. There will just be a section in the
> README about provisioning servers and deploys which will link to it.
>
> The same goes for any other server management software (Chef, Puppet,
> etc). Since there won't be anything in this repo to do with Ansible (other
> than the README), there really is no dependency anyway.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/roots/bedrock/issues/153#issuecomment-84733841>.
>


-- 
Sent from Gmail Mobile.

Have you listened to Arrested DevOps today?
http://www.arresteddevops.com

**Comment by francescolaffi** [comment]
You had me worried for a moment :p
