### ISSUE TITLE
php syntax error in application.php on line 11

### ISSUE THREAD

**Issue by jnor** [roots/bedrock#200]
Hi clean bedrock install I get this error:

Parse error: syntax error, unexpected '[', expecting ')' in /home/jn/test/new-website.dk/config/application.php on line 11

So I changed line 11 from this:
$dotenv->required(['DB_NAME', 'DB_USER', 'DB_PASSWORD', 'WP_HOME', 'WP_SITEURL']);

To this:
 $dotenv->required('DB_NAME', 'DB_USER', 'DB_PASSWORD', 'WP_HOME', 'WP_SITEURL');

Now works...

php -v
PHP 5.6.12 (cli) (built: Aug  6 2015 19:22:08) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by swalkinshaw** [comment]
I'm 99% sure that error is because of an older PHP version. You see that error when a PHP error doesn't support the short array syntax.

Your `php -v` shows 5.6.12 which should work but that's for CLI if you notice. Maybe your web server is running an older version? Try outputting `echo php_info();`.
