### ISSUE TITLE
Maybe require autoload.php in an mu-plugin instead of in wp-config.php

### ISSUE THREAD

**Issue by EmilEriksen** [roots/bedrock#310]
Right now autoload.php is loaded in wp-config.php before WordPress boots. This causes issues with some plugins that use the files feature of the composer autoloader (e.g. [Mailchimp for WordPress](https://github.com/ibericode/mailchimp-for-wordpress/blob/master/composer.json#L49-L55), [Carbon Fields](https://github.com/htmlburger/carbon-fields/blob/master/composer.json#L94-L97) and [WooCommerce PDF Invoices](https://github.com/baselbers/woocommerce-pdf-invoices/blob/master/composer.json#L23-L33)) to load files that are actually dependant on WP being loaded.

I'm not really sure if this is just bad practice by those plugins but I'm leaning towards it being more of an issue of when autoload.php is actually being loaded. After all the way we load WP now is a workaround and the way WP boots wasn't built with Composer in mind. Since we're the ones using a workaround we should also work around this. I feel like being unable to use the files feature when developing plugins and themes because of setups like Bedrock would be a shame. I also can't really think of any times where including the autoloader before WP is loaded is useful since all development with WP is pretty much in plugins and themes.

I'm currently testing a solution where I'm loading autoload.php from an mu-plugin instead and it seems to be working well. MU plugins are loaded in alphabetical order so including autoload.php in a MU plugin called something like `_autoload.php` would mean that the autoloader would still be loaded first in the vast majority of cases.

I would love to hear other opinions around this :)

**Comment by kalenjohnson** [comment]
First off, yes, if you have code that is being autoloaded and executing code right on load, that's not good. Autoloading is for having your language understand where to find code so you don't have to do it manually, but nothing should actually be happening when the autoloader is loaded. WP plugins don't necessarily follow [PSR-4](http://www.php-fig.org/psr/psr-4/), but there are some good guidelines there, specifically:

> Autoloader implementations MUST NOT throw exceptions, MUST NOT raise errors of any level, and SHOULD NOT return a value.

Looking at the issue you link on carbon-fields, it seems like they're going to have a fix for it. My suggestion would be that if a plugin is trying to execute code before it should (such as, adding a file to be autoloaded and executing code in that file), then use their wpackagist implementation so things are loaded when they are expected to be.

You'll note that WP plugins don't require any type of coding standard, but if you take a look at [PSR-1](http://www.php-fig.org/psr/psr-1/), one of the suggestions is this:

> A file SHOULD declare new symbols (classes, functions, constants, etc.) and cause no other side effects, or it SHOULD execute logic with side effects, but SHOULD NOT do both.

It's unfortunate that you've found so many plugins that are doing this. But if a plugin author wants to be able to utilize Composer, it should be able to be autoloaded early in the process. Take a look at other PHP frameworks and the Composer autoloader is one of the first things that happens.

I suppose it also comes down to dependencies. If it's a WP plugin, then it should get loaded as a WP plugin. If it's a Composer package, then it shouldn't necessarily rely on WP to function. And I say that because WP does not have any understanding of Composer or autoloading.

**Comment by EmilEriksen** [comment]
@kalenjohnson Thanks for you comment. Good points - I'm convinced.

I'm closing the issue since I feel like it's been established that it is in fact bad practice by the plugin developers and not a Bedrock issue.
