### ISSUE TITLE
is_plugin_active for bedrock

### ISSUE THREAD

**Issue by HarroH** [roots/bedrock#340]
Hi there,

We hit a small issue with a plugin that is depending on another plugin. Both plugins are must use plugins and are defined as such. However, the default function for wordpress 'is_plugin_active' doesn't seem to work for mu plugins in bedrock. So the 'sub' plugin for the other mu plugin is giving an error and disables itself. Is this suppose to work with bedrock or is there any workaround for this?

BR, Harro

**Comment by aaemnnosttv** [comment]
[`is_plugin_active`](https://developer.wordpress.org/reference/functions/is_plugin_active/#source) only checks for the presence of the plugin in the `active_plugins` option. Trying to use this function to check if an mu-plugin is active will fail because they are not included in this option since they are always on.

You should raise this as a question on [discourse](https://discourse.roots.io) as this isn't a bug with Bedrock.

**Comment by HarroH** [comment]
Never called it a bug. So it's not really an answer to the question. The function is_plugin_active is the default function for WP to check if plugins are on or off. Even though bedrock uses a different way to activate my plugins, I would expect to be able to use the default functions from wordpress to check if a plugin is active or not. If this is something that is just being looked over an nothing is being done with it, I feel it's a mayor flaw in the design. This basically makes a lot of plugins within the Wordpress directory useless when they are depended on another plugin. The only work around is not to make the plugins must use, which disregards the idea behind the mu plugins.

**Comment by chesio** [comment]
> The function is_plugin_active is the default function for WP to check if plugins are on or off.

Yes, but as @aaemnnosttv mentioned, the function is **designed** to work only with **normal** plugins, not must-use plugins. You should really read [the docs](https://developer.wordpress.org/reference/functions/is_plugin_active/).

If you need to use `is_plugin_active` within a plugin, you probably don't want this plugin to be a must-use plugin in the first place.

**Comment by mAAdhaTTah** [comment]
> Never called it a bug.

If it's not a bug, then it doesn't belong on the issue tracker. You should open a thread on [discourse](https://discourse.roots.io/).

**Comment by HarroH** [comment]
A you win! Try not to improve your framework. Just ignore it.

It logic that wordpress does only mention the /plugin/ folder, as they assume you stick with there folder structure. When you start manipulating the folder structure of a framework, it's not more then logic should consider all the functions that use this folder structure. But that's just my logic, based on all the very defence responses here, I believe I'm the only one who find this logical.

**Comment by retlehs** [comment]
@HarroH 

* you cleared out the issue template when you made this issue which told you not to post personal support requests on github
* you ignored two people that asked you to move the discussion to the proper place
* you then say we don't care about our "framework" because you're being told that you're in the wrong place for support?

🙄 🙄 🙄
