### ISSUE TITLE
Bedrock with polylang

### ISSUE THREAD

**Issue by tiagomatosweb** [roots/bedrock#341]
Hi,
I am using bedrock with polylang in a fresh installation with Twenty Seventeen theme.

Everything seems to work fine a part from that the menu does not change according to the current language.

Then, I installed wordpress again in a usual way and it worked.
Seems that there is an issue in bedrock when using Polylang.

Does anyone know what is happening?

Tks

**Comment by kevinbamber** [comment]
going to bump this as I seem to be experiencing the same thing with latest Bedrock, latest version of WP, latest version of Polylang on a fresh install.

It appears as though something within Bedrock core is preventing Polylang from updating its pll_language cookie; which is being used to determine what class to add to the active language on navbar; and determine what pll_e and pll__ strings to output.

I'm 100% that this is being caused by Bedrock since running a clean install of WP outside of Bedrock works as expected.

In both cases I am testing with a clean Twentyseventeen.

Has anyone found a solution to this, or might anyone be able to point me in the right direction? I've been exchanging a few emails with Polylang author @ https://github.com/polylang/polylang/issues/273

Cheers,
Kevin
