### ISSUE TITLE
[Feature/Question] Blade compatibility

### ISSUE THREAD

**Issue by OwenMelbz** [roots/bedrock#353]
Hey guys,

I've seen that your latest sage release comes with Blade templating support, however I was wondering what the scope of it is to either release the same feature for bedrock potentially? or maybe even a stand alone package?

Many thanks

**Comment by roots-ladybug** [comment]
Hi @OwenMelbz,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).
