### ISSUE TITLE
Hide composer file 

### ISSUE THREAD

**Issue by caco26i** [roots/bedrock#355]
## Feature Request

**Please provide use cases for changing the current behavior:**

Hide composer file
Example: https://roots.io/app/themes/roots/composer.json

**Comment by roots-ladybug** [comment]
Hi @caco26i,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).
