### ISSUE TITLE
Why not upgrade to phpdotenv 3.x ?

### ISSUE THREAD

**Issue by tristanbes** [roots/bedrock#411]
Hello,

Our dependency updater bot propose to upgrade **phpdotenv** from `2.x` to `3.x` 

Yet, you still have a dependency to 2.X only: https://semver.mwl.be/#?package=vlucas%2Fphpdotenv&version=%5E2.0.1&minimum-stability=stable

Is there any reason not to upgrade to phpdotenv 3.X on `roots/bedrock` ([besides the small BC breaks](https://github.com/vlucas/phpdotenv#upgrading-from-v2)) ?

Thanks.

**Comment by knowler** [comment]
From trying this myself on an actual project, I do know that there will be conflicts with https://github.com/PhilippBaschke/acf-pro-installer if you use that. Outside of that I believe the only change that needs to happen is in `config/application.php` since 3.0 changed how `Dotenv` is instantiated (check their README for the migration steps).

**Comment by tristanbes** [comment]
Yeah thanks for pointing that out, the question is more like, why is the core team of bedrock doesn't upgrade to 3.X for their `roots/bedrock` project.

**Comment by austinpray** [comment]
@tristanbes as a user: specifically what features in v3 are you missing from v2?

https://github.com/vlucas/phpdotenv/pull/311 Looks like a pretty solid feature

**Comment by tristanbes** [comment]
absolutely no feature is lacking for me. I just don't "like" starting new wordpress project with dependencies that are too behind. 

That's why I wanted to have your reasonning about not updating it (if there is any). :)
