### ISSUE TITLE
Support empty database prefix environment variable

### ISSUE THREAD

**Issue by devkinetic** [roots/bedrock#422]
**What is the current behavior?**
When setting the `DB_PREFIX=''` it is not respected and the default `'wp_'` is prepended.

**What is the expected or desired behavior?**
When uncommenting the `DB_PREFIX` and setting it to empty, it should be respected, and no prefix should be prepended.

**Please describe your local environment:**
Bedrock version: 1.12.2
WordPress version: 5.1
PHP version: 5.6
OS: OSX

**Comment by roots-ladybug** [comment]
Hi @devkinetic,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).

**Comment by devkinetic** [comment]
https://github.com/roots/bedrock/pull/423

**Comment by swalkinshaw** [comment]
Closed by https://github.com/roots/bedrock/pull/423
