### ISSUE TITLE
Variable in order to get the /web directory

### ISSUE THREAD

**Issue by tristanbes** [roots/bedrock#424]
## Submit a feature request or bug report

- [x] This is a feature request

---

Hello,

I need to create a custom filter to load a file that lives under `web/<FILE_TO_LOAD>`

Is there any constant or something else that i can use anywhere inside the theme that will always gives me the path to `web/` ?

Thanks

**Comment by roots-ladybug** [comment]
Hi @tristanbes,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).

**Comment by tristanbes** [comment]
Well i've decided to go with `Config::get('WP_CONTENT_DIR')` since there is no config for just only `$webroot_dir`

**Comment by QWp6t** [comment]
`$webroot_dir` is a global.

Or you could just create a constant if you prefer that.
