### ISSUE TITLE
Site health check (5.2) not present on production

### ISSUE THREAD

**Issue by tristanbes** [roots/bedrock#435]
Hello,

This bug report is about the Site Health check introduced in 5.2

I've noticed that in local developement, I can access to `/wp/wp-admin/site-health.php` + the item is present under the "Tools" menu.

As soon as I am on the production (`WP_ENV=production`) the menu item is no longer present, and the page `/wp/wp-admin/site-health.php` gives a 404 error or an authorization error (you don't have access to this page) although I'm an administrator.

Is this related to Bedrock ?

**Comment by retlehs** [comment]
Probably DISALLOW_FILE_MODS?

**Comment by roots-ladybug** [comment]
Hi @tristanbes,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).

**Comment by tristanbes** [comment]
`Config::define('DISALLOW_FILE_MODS', true);` which is what we want in a production environement, but I don't see the reason behind not showing an important page based on this constant which has absolutely nothing to do with the site health check feature. :) 

So WordPress side then ?

**Comment by Log1x** [comment]
https://core.trac.wordpress.org/ticket/47204
