### ISSUE TITLE
Media settings won't save

### ISSUE THREAD

**Issue by LarBearrr** [roots/bedrock#447]
## Description

When trying to update media settings under Settings>Media, my updated values do not save. 

## Steps to reproduce

1. Go to Settings>Media
2. Update the thumbnail image sizes
3. Click Save Changes
4. Page refreshes and the default values replace my changes

**Expected behavior:**
I need to be able to modify the image sizes for thumbnails and other image sizes.

**Actual behavior:**
My changes are not saved and/or are replaced by default values when trying to save.

**Reproduces how often:** 100%

## Versions

1.12.6: 2019-05-21

Thank you!

**Comment by roots-ladybug** [comment]
Hi @LarBearrr,
It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests. Use [Roots Discourse](https://discourse.roots.io/) to ask the Roots community for help, or [hire someone from the community](https://discourse.roots.io/c/jobs).
