### ISSUE TITLE
How do you use bedrock with plugins that have own libraries from composer?

### ISSUE THREAD

**Issue by katsar0v** [roots/bedrock#449]
I wanted to ask if anyone has idea what's the impact of having redundand libraries in bedrock and some plugins, my example:

I have a bedrock setup with some more libraries (for logging and other stuff), now I install MailPoet and WP SMTP, both plugins have own vendor/ folders with own libraries. Is composer taking care of the redundancy and does it load only one of the libraries?

**Comment by roots-ladybug** [comment]
Hi @katsar0v,
It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests. Use [Roots Discourse](https://discourse.roots.io/) to ask the Roots community for help, or [hire someone from the community](https://discourse.roots.io/c/jobs).

**Comment by katsar0v** [comment]
Is there a gitter channel for bedrock? I saw one only for sage

**Comment by retlehs** [comment]
https://discourse.roots.io/ :wave:
