### ISSUE TITLE
Don't lock roots/wordpress to a exact version in composer.json

### ISSUE THREAD

**Issue by roy-bongers** [roots/bedrock#500]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary
When creating a bedrock project `composer create-project roots/bedrock some-site` a composer.json is installed with the version of roots/wordpress locked to a specific version. Unless you change this WordPress will never be updated. Not even with Dependabot if I'm correct.

## Motivation
When a new version of WordPress is available is should be as easy as running `composer update roots/wordpress` and deploying to production. There should be no need to manually edit the composer.json file to update the version. It's important to keep WordPress updated and you don't want to risk running an old version because it's locked to that by default by bedrock.

I suggest changing the composer.json file to:
```JSON
    "roots/wordpress": "^5.3",
    "roots/wp-config": "^1.0.0",
    "roots/wp-password-bcrypt": "^1.0.0",
```

**Comment by austinpray** [comment]
IIRC the original reason why bedrock uses a fixed version is because WordPress does not follow semver. As such: setting the WordPress version to a semver version range could lead to undefined behavior. Maybe @roots/everyone can chime in to correct me on the history here.

* * *

>Not even with Dependabot if I'm correct.

Dependabot handles fixed versions correctly 👍 

![Capture](https://user-images.githubusercontent.com/2192970/77254874-b3905780-6c31-11ea-9c03-9b61cd97e85a.PNG)

https://github.com/roots/bedrock/pull/489

* * *

That said: perhaps it _would_ be prudent to consider setting the version range to something like `5.3.*`? That would enable `composer update roots/wordpress` to work as you expect.

If you wanted to bump beyond 5.3 you would do `composer require roots/wordpress:5.4.*` or let Dependabot or whatever bump it for you. An update like 5.3 -> 5.4 is never an automated affair so it requires manual attention anyway. If, for _your sites_, 5.3 -> 5.4 is simply a matter of bumping the version and deploying: feel free to change relax version range in your project.

Also related: #21

**Comment by swalkinshaw** [comment]
🤔 honestly I don't really remember discussion over specifying the exact version. We basically release a version of Bedrock for *every* WP release since Bedrock is meant to be used as a starter/boilerplate. But the same thing could be accomplished by just updating the lockfile (if we keep it).

**Comment by knowler** [comment]
> There should be no need to manually edit the composer.json file to update the version.

There _is_ no need to manually change `composer.json` to change the WordPress version. All can be done through Composer:

```bash
# Install Bedrock 1.10.0 (WordPress 5.0)
composer create-project roots/bedrock example.com 1.10.0
cd example.com

# Specifically require WordPress 5.3.2
composer require roots/wordpress:5.3.2

# Require the latest WordPress version and set just a major version constraint (i.e. currently ^5.3)
composer require roots/wordpress
```

`composer update <package>` updates the dependencies based on the contents of `composer.json` and with looser version constraints that could update `roots/wordpress`, but I think a fixed version and using `composer require` instead is a good idea.

> It's important to keep WordPress updated and you don't want to risk running an old version because it's locked to that by default by bedrock.

Yes, true, but, as well, with Bedrock we advocate setting intentional software requirements and not just blindly updating WordPress. In my experience, using Dependabot and some sort of CI (and further testing) works well for this.

**Comment by roy-bongers** [comment]
Thank you guys. I didn't know WordPress does not adhere semver versioning and isn't planning to do so. I can see how this could cause problems with composer. I'm used to running `composer update vendor/package` if I want to update a single package. Normally I only use `require` to install a new package. This feels like "the right way" thats why I get confused when I see the exact version locked in the json file.

I saw the other issue but the discussion was more about wether to add the composer.lock file to git or not. As Scott mentions, I also agree that the version to be installed should be locked in the lockfile and not so much in the .json file. It's good to hear Dependabot solves this just fine although I would assume Dependabot also uses semver to compare versions.

It all boils down to WordPress not adhering semver I guess. If they did there would be no problem is setting a version constraint like `"roots/wordpress": "^5.3",` just like Laravel does for example. I'm not sure what the right way is in this.

This issue is only about WordPress but with plugins / themes it would be the same I guess. You can't assume they use semver, you also can't assume they keep supporting older (major) versions so that makes me think. Should versions constraints for plugins also be strict when you require them? Or would you just set them to `*` and let Dependabot manage new releases so you never have to change the `composer.json` file unless you require a new plugin. I know `*` is a bad practice but it also doesn't make sense to have the exact version constraints both in the json and the lock file. The lock file contains all versions that eventually get installed.

If I look at [YoastSEO](https://github.com/Yoast/wordpress-seo/releases), they don't support semver and they don't seem to provide updates to older majors. So the only safe solution is to always run the latest version.

With WordPress (and plugins / themes) I always feel like I need to run the latest version to stay secure. So I have to admit I always set version constraints to `*` and have for example Dependabot manage updates. If something breaks I'll fix it or wait a little in the hope it'll get fixed.
