### ISSUE TITLE
Multisite support

### ISSUE THREAD

**Issue by swalkinshaw** [roots/bedrock#58]
There's a few features of Bedrock that might make some Multisite setups a problem:

* WP installed in subdirectory
* Custom content folder

Looking at some issues regarding this, it seems like MS support is still a bit of a mess. Related issues:

* https://core.trac.wordpress.org/ticket/27287
* https://core.trac.wordpress.org/ticket/23221
* https://core.trac.wordpress.org/ticket/26969

Here's a potential `mu-plugin` we may want to consider adding in Bedrock by default: https://gist.github.com/danielbachhuber/9379135

/cc @ddebernardy I'm hoping you can speak to/summarize some of the issues you've ran into and potential solutions.

**Comment by olivierhaustrate** [comment]
I'm encountering the same problem as described by @starise : the plugins' files are in the mu-plugins folder, but not listed in admin (plugin page).
I've updated the bedrock-autoloader.php based on the fix of @starise , but it's not solving my problem because I'm not using a multisites instal; I'm working on a subdomain (dev) for staging on the production server.
So the problem occurs because I have my wordpress install on a subdomain.
Did someone already found a way to solve that problem?

**Comment by zairl23** [comment]
How about nginx rewirte codes??

**Comment by swalkinshaw** [comment]
@zairl23 https://github.com/roots/bedrock-ansible/blob/master/roles/nginx/templates/wordpress_multisite_subdirectories.conf.j2
