### ISSUE TITLE
enqueue_scripts & enqueue_styles generates wrong URLs in admin

### ISSUE THREAD

**Issue by sebastiaandegeus** [roots/bedrock#72]
Many plugins use plugins_url() in their enqueue_scripts and enqueue_styles. The plugins urls seems ok when you var_dump it with a filter like this:

```
function filter_plugins_url( $url ) {
  var_dump($url);
  return $url;
}
add_filter( 'plugins_url', 'filter_plugins_url' );
```

Example with WP-SEO:
the var dump results in: `http://dev.domain.com/app/plugins/wordpress-seo/css/adminbar.css`

But weirdly the HTML source contains this:
`<link rel="stylesheet" href="/wp/app/plugins/wordpress-seo/css/adminbar.css?ver=1.5.2.8">`

Constants from the wp-config:
```
WP_HOME "http://dev.domain.com"
DOMAIN_CURRENT_SITE "http://dev.domain.com"
WP_SITEURL "http://dev.domain.com/wp
```

Conclusion:
WordPress is trying to be smart here and it looks like it makes the already absolute urls relative again but uses  WP_SITEURL for this and thus breaking the urls for this plugin assets.

**Comment by retlehs** [comment]
need to determine the steps / setup necessary to re-create this issue, since this issue doesn't exist on a vanilla bedrock + wordpress install

**Comment by retlehs** [comment]
not able to reproduce.

**Comment by retlehs** [comment]
ran into this on a install i migrated from a non-bedrock setup. it only happens in the admin, and the problem doesn't exist if i drop the DB and re-install wordpress (using the same code, plugins, theme, etc.)

definitely DB related. trying to track it down.

**Comment by retlehs** [comment]
jokes on me! this bug comes from the old roots starter theme that included relative urls functionality.

remove `add_theme_support('root-relative-urls');` from `lib/config.php` and then go ahead and use https://github.com/roots/soil if you want relative URLs that dont break things.

**Comment by MichaelHabib** [comment]
I had the same issue for all assets in theme & backend when trying to test bedrock from a subfolder such as MyDomain/wordpress/bedrock_test_folder/  
After digging deeper & finding out that plugin_url() uses the constant `WP_CONTENT_DIR` /wp-includes/default-constants.php , i did the following :

Added `Config::define('WP_CONTENT_URL', Config::get('WP_HOME').'app')` to my config/environments/development.php 

Now the `WP_CONTENT_DIR` constant is an absolute url to the correct files instead of the default relative `/app` url .

**Comment by davidwebca** [comment]
Yeah you're right. It's a Soil issue with relative URLs so I'll look into which hooks everything's happening go and create an issue there if anything.
